<?php

namespace AppBundle\Repository;

/**
 * VieDeMerdeTicketsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VieDeMerdeTicketsRepository extends \Doctrine\ORM\EntityRepository
{
      public function findTopPost()
    {
        $findTopPost = $this->createQueryBuilder('SELECT * FROM `vie_de_merde_tickets` ORDER BY `vie_de_merde_tickets`.`liketicket` DESC');
        return $findTopPost->getQuery()->getResult();
        // $builder = $this->createQueryBuilder('p','u','c')
        //     ->join('p.categories','c')
        //     ->join('p.user','u')
        //     ->orderBy('p.date', 'DESC');
        //
        // return = $builder->getQuery()->getResult();
    }
}
